package org.d0sl.examples.auto.drome;

/*Generated by MPS */

import javax.swing.ImageIcon;
import java.awt.Color;

/**
 * Represents a cell on the Autodrome world
 */
public class Cell extends VisualCell {
  private static ImageIcon[] carIcons = new ImageIcon[4];
  static {
    ClassLoader classLoader = Cell.class.getClassLoader();
    carIcons[Direction.north.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/car-north.png"));
    carIcons[Direction.east.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/car-east.png"));
    carIcons[Direction.south.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/car-south.png"));
    carIcons[Direction.west.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/car-west.png"));
  }
  private RoboCar car = null;
  private int row = -1;
  private int col = -1;
  public int getRow() {
    return row;
  }
  public void setRow(int row) {
    this.row = row;
  }
  public int getCol() {
    return col;
  }
  public void setCol(int col) {
    this.col = col;
  }
  public Cell() {
    init();
  }
  public boolean isCar() {
    return car != null;
  }
  protected Cell setCar(RoboCar car) {
    this.car = car;
    return this;
  }
  protected Cell unsetCar() {
    this.car = null;
    return this;
  }
  protected void init() {
    setBackground(Color.WHITE);
    if (car != null) {
      setIcon(Cell.carIcons[car.getDirection().ordinal()]);
    } else {
      setIcon(null);
    }
  }
  public RoboCar getCar() {
    return car;
  }
}
