package org.d0sl.examples.auto.drome;

/*Generated by MPS */

import javax.swing.ImageIcon;
import java.awt.Color;

public class RoadSign extends Cell {
  private static ImageIcon[] signIcons = new ImageIcon[4];
  static {
    ClassLoader classLoader = Cell.class.getClassLoader();
    signIcons[Direction.north.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/road-sign-north.png"));
    signIcons[Direction.east.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/road-sign-east.png"));
    signIcons[Direction.south.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/road-sign-south.png"));
    signIcons[Direction.west.ordinal()] = new ImageIcon(classLoader.getResource("autodrome/road-sign-west.png"));
  }
  private Direction direction;
  public Direction getDirection() {
    return direction;
  }
  public RoadSign(Direction direction) {
    this.direction = direction;
    init();
  }
  @Override
  protected void init() {
    if (direction != null && !(isCar())) {
      setIcon(RoadSign.signIcons[direction.ordinal()]);
    } else
    if (isCar()) {
      super.init();
    }
    setBackground(Color.GRAY);
  }
}
