package org.d0sl.examples.auto.drome;

/*Generated by MPS */

import org.d0sl.model.BaseObject;

/**
 * Represents a stupid robocar controlled by AIAutodrome of Autodrome
 */
@SuppressWarnings(value = "Duplicates")
public class RoboCar extends BaseObject {
  private int row;
  private int col;
  private Direction direction;
  public int getRow() {
    return row;
  }
  public void setRow(int row) {
    this.row = row;
  }
  public int getCol() {
    return col;
  }
  public void setCol(int col) {
    this.col = col;
  }
  public Direction getDirection() {
    return direction;
  }
  public void setDirection(Direction direction) {
    this.direction = direction;
  }
  public RoboCar(int row, int col) {
    this.row = row;
    this.col = col;
    this.direction = Direction.east;
  }
  public RoboCar(int row, int col, Direction direction) {
    this.row = row;
    this.col = col;
    this.direction = direction;
  }
  public RoboCar(RoboCar car) {
    this(car.row, car.col, car.direction);
  }
  public void turnLeft() {
    switch (this.direction) {
      case north:
        this.direction = Direction.west;
        break;
      case east:
        this.direction = Direction.north;
        break;
      case south:
        this.direction = Direction.east;
        break;
      case west:
        this.direction = Direction.south;
      default:
    }
  }
  public void turnRight() {
    switch (this.direction) {
      case north:
        this.direction = Direction.east;
        break;
      case east:
        this.direction = Direction.south;
        break;
      case south:
        this.direction = Direction.west;
        break;
      case west:
        this.direction = Direction.north;
      default:
    }
  }
  public void move() {
    switch (direction) {
      case north:
        row -= 1;
        break;
      case east:
        col += 1;
        break;
      case south:
        row += 1;
        break;
      case west:
        col -= 1;
        break;
      default:
    }
  }
}
