package org.d0sl.examples.auto.drome;

/*Generated by MPS */

import javax.swing.ImageIcon;
import java.awt.Color;

public class Wall extends Cell {
  private static ImageIcon wallIcon;
  static {
    ClassLoader classLoader = Cell.class.getClassLoader();
    wallIcon = new ImageIcon(classLoader.getResource("autodrome/wall.png"));
  }
  @Override
  public boolean isCar() {
    return false;
  }
  @Override
  protected Cell setCar(RoboCar car) {
    throw new RuntimeException("Robocar cannot be placed on a wall.");
  }
  @Override
  protected void init() {
    setBackground(Color.RED);
    setIcon(wallIcon);
  }
}
