package org.d0sl.examples.chess.pieces;

/*Generated by MPS */

import org.d0sl.examples.chess.chessboard.Player;
import org.d0sl.examples.chess.chessboard.Position;
import java.awt.Image;

/**
 * 
 */
public abstract class Piece {
  protected Player pieceColor;
  protected Position currentPos;
  public Piece(Player color, Position position) {
    currentPos = position;
    pieceColor = color;
  }
  public abstract Image getImage();
  public Player getPieceColor() {
    return pieceColor;
  }
  public Position getPosition() {
    return currentPos;
  }
}
