package org.d0sl.examples.chess.view;

/*Generated by MPS */

import java.awt.Color;
import java.awt.Graphics;

/**
 * 
 */
public abstract class BoardItem {
  protected Color color;
  public BoardItem(Color color) {
    this.color = color;
  }
  public abstract void draw(Graphics g);
}
