package org.d0sl.examples.chess.view;

/*Generated by MPS */

import java.awt.Color;
import java.awt.Image;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;

/**
 * 
 */
public class ChessSquare extends BoardItem {
  public static final int SQUARE_SIZE = 60;
  private Color highlightColor = Color.GREEN;
  private Color posMoveColor = Color.BLUE;
  private Image pieceImage;
  private int x;
  private int y;
  public ChessSquare(Color color, int x, int y) {
    super(color);
    this.x = x;
    this.y = y;
  }
  public void setPieceImage(Image image) {
    this.pieceImage = image;
  }
  @Override
  public void draw(Graphics g) {
    Graphics2D g2 = (Graphics2D) g;
    Rectangle2D r = new Rectangle2D.Double(x, y, SQUARE_SIZE, SQUARE_SIZE);
    g2.setColor(color);
    g2.fill(r);
    // Draw piece 
    if (pieceImage != null) {
      g.drawImage(pieceImage, x, y, null);
    }
  }
}
