package org.d0sl.examples.chess.view;

/*Generated by MPS */

import javax.swing.JFrame;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 * 
 */
public class ChessFrame extends JFrame {
  public ChessFrame() {
    setLocation(500, 300);
    setTitle("Arrangement of chess queens");
    setDefaultCloseOperation(EXIT_ON_CLOSE);
    setVisible(true);
    setLayout(new BorderLayout());
  }
  public void addPanelNorth(JPanel panel) {
    add(panel, BorderLayout.NORTH);
    pack();
  }
  public void addPanelCenter(JPanel panel) {
    getContentPane().add(panel, BorderLayout.CENTER);
    pack();
  }
}
