package org.d0sl.examples.chess.view;

/*Generated by MPS */

import javax.swing.JPanel;
import javax.swing.JButton;

/**
 * 
 */
public class NavigationPanel extends JPanel {
  private JButton arrangeButton;
  public NavigationPanel() {
    init();
  }
  public JButton getArrangeButton() {
    return arrangeButton;
  }
  private void init() {
    arrangeButton = new JButton("Arrange 8 queens");
    add(arrangeButton);
  }
}
