package org.d0sl.examples.chess.chessboard;

/*Generated by MPS */

import org.d0sl.examples.chess.pieces.Piece;
import java.util.ArrayList;

/**
 * 
 */
public class Chessboard {
  private Piece[][] pieces = new Piece[8][8];
  public void setPieces(Piece[][] pieces) {
    this.pieces = pieces;
  }
  public Piece[][] getPieces() {
    return pieces;
  }
  public ArrayList<Piece> getPieceList() {
    ArrayList<Piece> pieceList = new ArrayList();
    for (int x = 0; x < 8; x++) {
      for (int y = 0; y < 8; y++) {
        if (pieces[x][y] != null) {
          pieceList.add(pieces[x][y]);
        }
      }
    }
    return pieceList;
  }
}
