package org.d0sl.examples.chess.chessboard;

/*Generated by MPS */

import java.util.Objects;

/**
 * Represents a piece position on the chessboard
 */
public class Position {
  private int row;
  private int column;
  public Position(int row, int column) {
    this.row = row;
    this.column = column;
  }
  public Position(Position other) {
    this.row = other.row;
    this.column = other.column;
  }
  public int getColumn() {
    return column;
  }
  public int getRow() {
    return row;
  }
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Position position = (Position) o;
    return row == position.row && column == position.column;
  }
  @Override
  public int hashCode() {
    return Objects.hash(row, column);
  }
}
