package org.d0sl.examples.chess;

/*Generated by MPS */

import org.d0sl.model.BaseObject;

/**
 * Represents a chess queen
 */
public class ChessQueen extends BaseObject {
  private int col;
  private int raw;
  public ChessQueen(int col, int raw) {
    super("ChessDSL", "ChessQueen");
    this.col = col;
    this.raw = raw;
  }
  @Override
  public String toString() {
    return "ChessQueen{col=" + col + ", raw=" + raw + '}';
  }
  public int getCol() {
    return col;
  }
  public int getRaw() {
    return raw;
  }
}
