package org.d0sl.examples.chess;

/*Generated by MPS */

import org.d0sl.model.BaseObject;
import org.d0sl.examples.chess.chessboard.Chessboard;

/**
 * Represents a chess board
 */
public class ChessBoard extends BaseObject {
  private Chessboard board;
  public ChessBoard(Chessboard board) {
    super("ChessDSL", "ChessBoard");
    this.board = board;
  }
  public Chessboard getBoard() {
    return board;
  }
}
